# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 725dd65be13cdc7f04cbce6820a9fbc05037c1f73a340b816fac64013a8d4e88d585c01a5398266343abdb7ba4693f32ee1b89101cf570c3cfe9904d95afece3

test:
  secret_key_base: 10e5b4561cd5006eec75ff8055eb9259476e7050645f1fab8b17e24fe30c01ecf63699ea75ebb1b7b419a07d37f9e72d2ae908ed8e3a2f15d20f034ae4482553

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
